package venusbackend.assembler

import venusbackend.assembler.pseudos.* // ktlint-disable no-wildcard-imports

/** Describes each instruction for writing */
enum class PseudoDispatcher(val pw: PseudoWriter) {
    beqz(BEQZ),
    bgez(BGEZ),
    bgt(BGT),
    bgtu(BGTU),
    bgtz(BGTZ),
    ble(BLE),
    bleu(BLEU),
    blez(BLEZ),
    bltz(BLTZ),
    bnez(BNEZ),
    call(CALL),
    jal(JAL),
    jalr(JALR),
    j(J),
    jr(JR),
    la(LA),
    lb(Load),
    lbu(Load),
    lh(Load),
    lhu(Load),
    li(LI),
    lw(Load),
    ld(Load),
    mv(MV),
    neg(NEG),
    negw(NEGW),
    nop(NOP),
    not(NOT),
    ret(RET),
    sb(Store),
    sextw(SEXTW),
    seqz(SEQZ),
    sgtz(SGTZ),
    sh(Store),
    sltz(SLTZ),
    snez(SNEZ),
    sw(Store),
    sd(Store),
    tail(TAIL),
    /* nonstandard */
    seq(SEQ),
    sge(SGE),
    sgeu(SGE),
    sgt(SGT),
    sgtu(SGT),
    sle(SLE),
    sleu(SLE),
    sne(SNE),
    fmvs(FMVS),
    fabss(FABSS),
    fnegs(FNEGS),
    fmvd(FMVD),
    fabsd(FABSD),
    fnegd(FNEGD),
    flw(Load),
    fld(Load),
    fsw(Store),
    fsd(Store)
    ;
}
